---
name: build-package
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: ['main']
    tags: [ v* ]
jobs:
  build:
    runs-on: "macos-14"
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - uses: actions/checkout@v4
      - run:
          fastlane tests